# Este é um fluxo de trabalho básico para ajudar você a começar com GitHub Actions

name: CI

# Controla quando o fluxo de trabalho será executado
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz check-out do repositório
      - uses: actions/checkout@v3

      # Executa um comando simples
      - name: Executa um script de uma linha
        run: echo "Olá, mundo!"

      # Executa múltiplos comandos
      - name: Executa um script multi-linha
        run: |
          echo "Adicionar outras ações para construir,"
          echo "testar e implantar seu projeto."
